### ISSUE TITLE
Home button is not working. 

### ISSUE THREAD

**Issue by Aditya-Raghuvanshi** [Rakesh9100/Click-The-Edible-Game#15] opened 2023-02-13 06:39 UTC
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The Home icon or button is not working after we choose the fruits or vegetables for the restart of the game .

https://user-images.githubusercontent.com/103103243/218387841-4e6498a1-0e5d-43bc-a2b1-f685b4d2bdf0.mp4

### Screenshots

![image](https://user-images.githubusercontent.com/103103243/218388099-e88ae511-dfa4-4de2-b49e-8b05e9ad009e.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Aditya-Raghuvanshi** [comment] 2023-02-13 06:59
i want to work on this issue.

**Comment by AK-shat-JAIN** [comment] 2023-02-14 18:31
I want to do this

**Comment by Rakesh9100** [comment] 2023-02-14 18:35
@AK-shat-JAIN Pls comment if you are working under JWOC

**Comment by Aditya-Raghuvanshi** [comment] 2023-02-14 18:39
i want to work on this issue under JWOC

**Comment by purbakundu** [comment] 2023-02-14 19:23
i want to contribute

**Comment by sagnik3788** [comment] 2023-02-14 19:33
i want to work on this  under jwoc

**Comment by Harry629** [comment] 2023-02-14 20:39
I want to work on this issue under JWOC

**Comment by Rakesh9100** [comment] 2023-02-15 14:10
@Aditya-Raghuvanshi Assigning to you, Good luck.

**Comment by Rakesh9100** [comment] 2023-02-15 15:05
Don't worry. It will be added. You just start working. @Aditya-Raghuvanshi

**Comment by Shreyan-12345** [comment] 2023-02-15 16:36
@Aditya-Raghuvanshi if the issue is not solve pls assign it to me , i am a contributor under JWOC

**Comment by Rakesh9100** [comment] 2023-02-16 07:07
> @Rakesh9100 if the issue is not solve pls assign it to me , i am a contributor under JWOC

Sure @Shreyan-12345, but the one who comments first will be assigned first and then the next to next.

**Comment by AK-shat-JAIN** [comment] 2023-02-16 12:57
> @AK-shat-JAIN Pls comment if you are working under JWOC

@Rakesh9100 yes I am under JWOC please assign it to me

**Comment by Rakesh9100** [comment] 2023-02-16 13:07
> > @AK-shat-JAIN Pls comment if you are working under JWOC
> 
> @Rakesh9100 yes I am under JWOC please assign it to me

You haven't replied in 24 hrs, so assigned to other, If he can't do then will surely assign to you

**Comment by Rakesh9100** [comment] 2023-02-16 13:15
@Aditya-Raghuvanshi Status of your work, since this is an easy task and only 1 day is to be provided

**Comment by Aditya-Raghuvanshi** [comment] 2023-02-16 15:14
> @Aditya-Raghuvanshi Status of your work, since this is an easy task and only 1 day is to be provided

i am facing some problem like, when working in files inside my vs code, some code is not visible like code of pause button ...but when i open through live server it is their. and to solve the bug i have tried to add event listener to the home button but it still not able to recognise it as button.

**Comment by Aditya-Raghuvanshi** [comment] 2023-02-16 17:54
> Oh okay. See the pause button was merged yesterday so pull the project first to get the updated code and then work on if facing issues @Aditya-Raghuvanshi

ok .

**Comment by Rakesh9100** [comment] 2023-02-16 19:48
> 
> ok .

Make the PR by today, else will be passed on. @Aditya-Raghuvanshi

**Comment by AK-shat-JAIN** [comment] 2023-02-16 23:28
> > > @AK-shat-JAIN Pls comment if you are working under JWOC
> > 
> > 
> > @Rakesh9100 yes I am under JWOC please assign it to me
> 
> You haven't replied in 24 hrs, so assigned to other, If he can't do then will surely assign to you @AK-shat-JAIN

Ok sir

**Comment by AK-shat-JAIN** [comment] 2023-02-18 06:16
Sr 

> > ok .
> 
> Make the PR by today, else will be passed on. @Aditya-Raghuvanshi
@Rakesh9100 
This issue is already sorted

**Comment by Rakesh9100** [comment] 2023-02-18 06:19
Yes👍 @AK-shat-JAIN

**Closed by Rakesh9100** 2023-02-18 06:19 UTC
Labels: duplicate 🔁
